image: frolvlad/alpine-gxx

# Install dependencies for build up front
before_script:
  - apk update
  - apk add make cmake

test:
  tags:
    - docker
  script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake .. -G "Unix Makefiles"
    - make -j2
    - ctest

build:
  tags:
    - docker
  script:
    - echo "CMake Build"
