image: gcc:9

# Install dependencies for build up front
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

test:
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake .. -G "Unix Makefiles"
    - make -j2
    - ctest

build:
  tags:
    - docker
  script:
    - echo "CMake Build"
