image: frolvlad/alpine-gxx

# Install dependencies for build up front
before_script:
  - apk update
  - apk add git make cmake mesa mesa-dev lua lua-dev libx11-dev libxext-dev clang
  - apk add physfs physfs-dev physfs-static --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

test:
  tags:
    - docker
  script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake .. -G "Unix Makefiles"
    - make -j2
    - ctest

build:
  tags:
    - docker
  script:
    - echo "CMake Build"
