image: gcc:9

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

test:
  tags:
    - docker
  script:
    - cmake --version

build:
  tags:
    - docker
  script:
    - echo "CMake Build"
