image: gcc:latest

# Install dependencies for build up front
before_script:
  - uname --all
  - apt update -qq
  - apt install -y -qq git make lua5.3 lua5.3-dev libx11-dev libxext-dev clang
  - apt install -y -qq cppcheck libphysfs-dev
  - apt install -y -qq libtbb-dev snapd
  - systemctl restart snapd.service
  - snap install cmake --classic

# Run unit tests (soon -> run linter and formatting)
test:
  tags:
    - docker
  script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake .. -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
    - make -j4
    - ctest
