image: gcc:latest

# Install dependencies for build up front
before_script:
  - apt update
  - apt upgrade
  - apt install git make cmake mesa mesa-dev lua lua-dev libx11-dev libxext-dev clang
  - apt install cppcheck physfs physfs-dev physfs-static
  - apt install libtbb libtbb-dev

# Run unit tests (soon -> run linter and formatting)
test:
  tags:
    - docker
  script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake .. -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
    - make -j4
    - ctest
